[package]
name = "demo_2d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[dev-dependencies]

[dependencies]
bevy = { version = "0.5.0" }
heron = { version = "0.11.0", features = ["2d"] }